name: Angular App Migration

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: '18.19.1' # or any other version you prefer
      - name: Install Http-server
        run: npm install -g http-server
      - name: moving to path
        run: cd dist/migration-process/browser
      - name: Build the application
        run: http-server